.TH "src/parsing Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexpand_home\&.c\fP"
.br
.ti -1c
.RI "file \fBexpand_variable\&.c\fP"
.br
.ti -1c
.RI "file \fBft_split_charset\&.c\fP"
.br
.ti -1c
.RI "file \fBfunctions_utils_parsing\&.c\fP"
.br
.ti -1c
.RI "file \fBparsing\&.c\fP"
.br
.ti -1c
.RI "file \fBparsing_quotes_double\&.c\fP"
.br
.ti -1c
.RI "file \fBquotes\&.c\fP"
.br
.in -1c
