.TH "src/env Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunctions_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBfunctions_utils_env\&.c\fP"
.br
.ti -1c
.RI "file \fBget_env\&.c\fP"
.br
.ti -1c
.RI "file \fBsort_env\&.c\fP"
.br
.in -1c
