.TH "src/garbage Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/garbage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgarbage\&.c\fP"
.br
.ti -1c
.RI "file \fBgarbage_stack\&.c\fP"
.br
.ti -1c
.RI "file \fBgarbage_utils\&.c\fP"
.br
.in -1c
