.TH "tests/src/parsing_quotes_double Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/parsing_quotes_double Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtesting_parsing_quotes_double\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_fx_printing\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_pars_doub_fx1\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_pars_doub_fx2\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_pars_sing_fx1\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_pars_sing_fx2\&.c\fP"
.br
.in -1c
