.TH "tests/src/file Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/file Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtesting_file\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_file\&.c\fP"
.br
.ti -1c
.RI "file \fBtests_heredoc\&.c\fP"
.br
.in -1c
