.TH "src/builtins Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBexport\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_cd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_echo\&.c\fP"
.br
.ti -1c
.RI "file \fBft_env\&.c\fP"
.br
.ti -1c
.RI "file \fBft_exit\&.c\fP"
.br
.ti -1c
.RI "file \fBft_pwd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_unset\&.c\fP"
.br
.ti -1c
.RI "file \fBft_which\&.c\fP"
.br
.in -1c
