.TH "src/env Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcopy_env\&.c\fP"
.br
.ti -1c
.RI "file \fBcreate_str_with_params\&.c\fP"
.br
.ti -1c
.RI "file \fBenv_to_array\&.c\fP"
.br
.ti -1c
.RI "file \fBfree_env\&.c\fP"
.br
.ti -1c
.RI "file \fBfunctions_utils\&.c\fP"
.br
.ti -1c
.RI "file \fBmanipulation_params\&.c\fP"
.br
.ti -1c
.RI "file \fBmanipulation_var\&.c\fP"
.br
.ti -1c
.RI "file \fBsearch_env\&.c\fP"
.br
.ti -1c
.RI "file \fBset_env\&.c\fP"
.br
.ti -1c
.RI "file \fBsort_env\&.c\fP"
.br
.ti -1c
.RI "file \fBsupp_var_in_env\&.c\fP"
.br
.ti -1c
.RI "file \fBswap_env\&.c\fP"
.br
.ti -1c
.RI "file \fBupdate_shlvl\&.c\fP"
.br
.in -1c
