.TH "src/exec Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommand\-utils\&.c\fP"
.br
.ti -1c
.RI "file \fBexec\-utils\&.c\fP"
.br
.ti -1c
.RI "file \fBexec\&.c\fP"
.br
.ti -1c
.RI "file \fBexec_extern\&.c\fP"
.br
.ti -1c
.RI "file \fBexec_pipeline\&.c\fP"
.br
.ti -1c
.RI "file \fBft_dups\&.c\fP"
.br
.ti -1c
.RI "file \fBsearch_command\&.c\fP"
.br
.in -1c
