.TH "src/file Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfile\-general\&.c\fP"
.br
.ti -1c
.RI "file \fBfile\&.c\fP"
.br
.ti -1c
.RI "file \fBfile_build\&.c\fP"
.br
.ti -1c
.RI "file \fBfile_print\&.c\fP"
.br
.ti -1c
.RI "file \fBfile_verify_access\&.c\fP"
.br
.ti -1c
.RI "file \fBft_file_tokens\&.c\fP"
.br
.ti -1c
.RI "file \fBheredoc\&.c\fP"
.br
.ti -1c
.RI "file \fBtmp_generator\&.c\fP"
.br
.in -1c
