.TH "tests/src Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBfile\fP"
.br
.ti -1c
.RI "directory \fBparsing_quotes_double\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBtesting_lexer\&.c\fP"
.br
.in -1c
