.TH "inc Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuiltins\&.h\fP"
.br
.ti -1c
.RI "file \fBdata_structure\&.h\fP"
.br
.ti -1c
.RI "file \fBenv\&.h\fP"
.br
.ti -1c
.RI "file \fBexec\&.h\fP"
.br
.ti -1c
.RI "file \fBfile\&.h\fP"
.br
.ti -1c
.RI "file \fBgarbage\&.h\fP"
.br
.ti -1c
.RI "file \fBminishell\&.h\fP"
.br
.ti -1c
.RI "file \fBparsing\&.h\fP"
.br
.in -1c
