.TH "src Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbuiltins\fP"
.br
.ti -1c
.RI "directory \fBenv\fP"
.br
.ti -1c
.RI "directory \fBexec\fP"
.br
.ti -1c
.RI "directory \fBfile\fP"
.br
.ti -1c
.RI "directory \fBgarbage\fP"
.br
.ti -1c
.RI "directory \fBlexer\fP"
.br
.ti -1c
.RI "directory \fBparsing\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_free\-utils\&.c\fP"
.br
.ti -1c
.RI "file \fBft_free\&.c\fP"
.br
.ti -1c
.RI "file \fBft_print_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBminishell\&.c\fP"
.br
.RI ": Main program of the Minishell "
.ti -1c
.RI "file \fBprompt\&.c\fP"
.br
.ti -1c
.RI "file \fBread_context\&.c\fP"
.br
.ti -1c
.RI "file \fBsignals\&.c\fP"
.br
.ti -1c
.RI "file \fBtoken\-utils\&.c\fP"
.br
.in -1c
