.TH "src/builtins/export Directory Reference" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/export Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcheck_args_export\&.c\fP"
.br
.ti -1c
.RI "file \fBft_build_elements\&.c\fP"
.br
.ti -1c
.RI "file \fBft_export\&.c\fP"
.br
.ti -1c
.RI "file \fBprint_export\&.c\fP"
.br
.in -1c
