.TH "inc/builtins.h" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/builtins.h
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_exit\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Function to exit the program\&. "
.ti -1c
.RI "int \fBft_echo\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Echo with -n option OPTIONS : -n : print without the triling newline\&. "
.ti -1c
.RI "int \fBft_which\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Says if the command are built-in commands or not\&. "
.ti -1c
.RI "int \fBft_export\fP (\fBt_data\fP *data, char **array)"
.br
.ti -1c
.RI "int \fBft_env\fP (\fBt_data\fP *data, char **array)"
.br
.ti -1c
.RI "int \fBft_unset\fP (\fBt_data\fP *data, char **array)"
.br
.ti -1c
.RI "int \fBft_pwd\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Print the current working directory\&. "
.ti -1c
.RI "int \fBft_cd\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Implementatin of cd builtin of shell\&. "
.ti -1c
.RI "void \fBft_exit_int\fP (\fBt_garbage\fP *garbage, int value)"
.br
.RI "Short ft_exit that uses only int noreturn attribute is to prevent -Wmissing-noreturn flag from flag -Weverything of debug-cc\&. "
.ti -1c
.RI "void \fBft_exit_int_np\fP (\fBt_garbage\fP *garbage, int value)"
.br
.RI "Short ft_exit that uses only int but don't say it's name\&. "
.ti -1c
.RI "void \fBchange_cwd\fP (\fBt_data\fP *data, t_bool is_pwd)"
.br
.RI "Change the values of ENV VAR\&. "
.ti -1c
.RI "int \fBchange_cwd_to_home\fP (\fBt_env_vars\fP *env)"
.br
.ti -1c
.RI "int \fBchange_cwd_to_previous_cwd\fP (\fBt_env_vars\fP *env)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
