.TH "src/builtins/export/check_args_export.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/export/check_args_export.c
.SH SYNOPSIS
.br
.PP
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcheck_args_export\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int check_args_export (const char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
