.TH "src/exec/command-utils.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/command-utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'stdio\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBprint_command\fP (\fBt_command\fP *command)"
.br
.RI "Print the command structure with it's tokens\&. "
.ti -1c
.RI "ssize_t \fBprint_commands\fP (\fBt_command\fP **command)"
.br
.RI "Print the commands structure with it's tokens\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
