.TH "src/env/copy_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/copy_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_env_vars\fP * \fBcopy_env\fP (\fBt_garbage\fP *garbage, \fBt_env_vars\fP *env)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_env_vars\fP * copy_env (\fBt_garbage\fP * garbage, \fBt_env_vars\fP * env)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
