.TH "src/env/create_str_with_params.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/create_str_with_params.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcreate_str_with_params\fP (\fBt_garbage\fP *garbage, \fBt_params\fP *params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * create_str_with_params (\fBt_garbage\fP * garbage, \fBt_params\fP * params)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
