.TH "inc/data_structure.h" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/data_structure.h
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_data\fP"
.br
.ti -1c
.RI "struct \fBs_command\fP"
.br
.RI "Structure that handles all the command and there contents\&. "
.ti -1c
.RI "struct \fBs_token\fP"
.br
.RI "Basic structure of linked list of strings\&. "
.ti -1c
.RI "struct \fBs_lexer_state\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_TOKENS_LEX\fP   1024"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_tmp\fP \fBt_tmp\fP"
.br
.ti -1c
.RI "typedef struct \fBs_file\fP \fBt_file\fP"
.br
.ti -1c
.RI "typedef struct \fBs_element\fP \fBt_element\fP"
.br
.ti -1c
.RI "typedef struct \fBs_garbage\fP \fBt_garbage\fP"
.br
.ti -1c
.RI "typedef struct \fBs_env_vars\fP \fBt_env_vars\fP"
.br
.ti -1c
.RI "typedef struct \fBs_var\fP \fBt_var\fP"
.br
.ti -1c
.RI "typedef struct \fBs_lexer_state\fP \fBt_lexer_state\fP"
.br
.ti -1c
.RI "typedef struct \fBs_command\fP \fBt_command\fP"
.br
.ti -1c
.RI "typedef struct \fBs_params\fP \fBt_params\fP"
.br
.ti -1c
.RI "typedef struct \fBs_token\fP \fBt_token\fP"
.br
.ti -1c
.RI "typedef struct \fBs_data\fP \fBt_data\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBs_command\fP \fBt_command\fP"

.SS "typedef struct \fBs_data\fP \fBt_data\fP"

.SS "typedef struct \fBs_element\fP \fBt_element\fP"

.SS "typedef struct \fBs_env_vars\fP \fBt_env_vars\fP"

.SS "typedef struct \fBs_file\fP \fBt_file\fP"

.SS "typedef struct \fBs_garbage\fP \fBt_garbage\fP"

.SS "typedef struct \fBs_lexer_state\fP \fBt_lexer_state\fP"

.SS "typedef struct \fBs_params\fP \fBt_params\fP"

.SS "typedef struct \fBs_tmp\fP \fBt_tmp\fP"

.SS "typedef struct \fBs_token\fP \fBt_token\fP"

.SS "typedef struct \fBs_var\fP \fBt_var\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
