.TH "src/exec/exec.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/exec.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprepare_command\fP (\fBt_command\fP *command, int ret)"
.br
.RI "Prepare the command for \fBsearch_command()\fP "
.ti -1c
.RI "int \fBprepare_command_forks\fP (\fBt_command\fP *command, int ret)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int prepare_command (\fBt_command\fP * command, int ret)"

.PP
Prepare the command for \fBsearch_command()\fP 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP command structure 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "int prepare_command_forks (\fBt_command\fP * command, int ret)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
