.TH "src/parsing/expand_home.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing/expand_home.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBexpand_tildes_tokens\fP (char **tokens)"
.br
.RI "Expands all the tildes found in array with HOME\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char ** expand_tildes_tokens (char ** tokens)"

.PP
Expands all the tildes found in array with HOME\&. 
.PP
\fBParameters\fP
.RS 4
\fItokens\fP array of strings 
.RE
.PP
\fBReturns\fP
.RS 4
char** tokens if OK, NULL otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
