.TH "src/parsing/expand_variable.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing/expand_variable.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'parsing\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBsearch_env_str\fP (\fBt_garbage\fP *garbage, \fBt_env_vars\fP *env, const char *var, size_t size)"
.br
.ti -1c
.RI "char * \fBhandle_expand\fP (\fBt_data\fP *data, char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char * search_env_str (\fBt_garbage\fP * garbage, \fBt_env_vars\fP * env, const char * var, size_t size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
