.TH "src/file/file.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file/file.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbuild_file_access\fP (\fBt_file\fP *file)"
.br
.RI "Build the file using access and check permissions\&. "
.ti -1c
.RI "\fBt_file\fP * \fBfile_parser\fP (\fBt_file\fP *file)"
.br
.RI "Parse the file structure\&. "
.ti -1c
.RI "void * \fBadd_file\fP (\fBt_garbage\fP *garbage, \fBt_command\fP *command, \fBt_token\fP *token, \fBt_file\fP **command_file)"
.br
.RI "Add a file to the stack given in param, each file added is at the beginning of the stack (reverse order) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
