.TH "src/file/file_build.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file/file_build.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbuild_files_redirection\fP (\fBt_data\fP *data)"
.br
.RI "Adds files to the file redirection structure\&. "
.ti -1c
.RI "int \fBbuild_files_data\fP (\fBt_command\fP *command)"
.br
.RI "Build the data around the files in all commands\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
