.TH "src/env/free_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/free_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_params\fP (\fBt_garbage\fP *garbage, \fBt_params\fP *element)"
.br
.ti -1c
.RI "void \fBfree_env\fP (\fBt_garbage\fP *garbage, \fBt_env_vars\fP *env)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_env (\fBt_garbage\fP * garbage, \fBt_env_vars\fP * env)"

.SS "void free_params (\fBt_garbage\fP * garbage, \fBt_params\fP * element)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
