.TH "src/builtins/export/ft_build_elements.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/export/ft_build_elements.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBbuild_elements\fP (char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char ** build_elements (char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
