.TH "src/builtins/ft_cd.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/ft_cd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include <linux/limits\&.h>\fP
.br
\fR#include <limits\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_cd\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Implementatin of cd builtin of shell\&. "
.ti -1c
.RI "void \fBchange_cwd\fP (\fBt_data\fP *data, t_bool is_pwd)"
.br
.RI "Change the values of ENV VAR\&. "
.ti -1c
.RI "int \fBchange_cwd_to_home\fP (\fBt_env_vars\fP *env)"
.br
.ti -1c
.RI "int \fBchange_cwd_to_previous_cwd\fP (\fBt_env_vars\fP *env)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
