.TH "src/builtins/ft_cd.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/ft_cd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_cd\fP (char **array)"
.br
.RI "Implementatin of cd builtin of shell\&. "
.ti -1c
.RI "int \fBft_pwd\fP (char **array)"
.br
.RI "Print the current working directory\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_cd (char ** array)"

.PP
Implementatin of cd builtin of shell\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP array of strings 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 OK, 1 otherwise 
.RE
.PP

.SS "int ft_pwd (char ** array)"

.PP
Print the current working directory\&. 
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
