.TH "src/exec/ft_dups.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/ft_dups.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBhandle_redirections\fP (\fBt_garbage\fP *garbage, \fBt_command\fP *command, int fd_backup[2])"
.br
.RI "Create and redirect inputs and outputs needed for the command\&. "
.ti -1c
.RI "void \fBreset_redirection\fP (\fBt_garbage\fP *garbage, \fBt_command\fP *command, int fd_backup[2], unsigned char i)"
.br
.RI "Reset redirections by default values Replace the new redirections by stdin and stdout\&. "
.ti -1c
.RI "int \fBhandle_redirections_forks\fP (\fBt_garbage\fP *garbage, \fBt_command\fP *command)"
.br
.RI "Create and redirect inputs and outputs needed for the command\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
