.TH "src/builtins/export/ft_export.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/export/ft_export.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_export\fP (\fBt_data\fP *data, char **array)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
