.TH "src/builtins/ft_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/ft_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_export\fP (char **array)"
.br
.ti -1c
.RI "int \fBft_env\fP (char **array)"
.br
.ti -1c
.RI "int \fBft_unset\fP (char **array)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_env (char ** array)"

.SS "int ft_export (char ** array)"

.SS "int ft_unset (char ** array)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
