.TH "src/builtins/ft_echo.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/ft_echo.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_echo\fP (char **array)"
.br
.RI "Echo with -n option OPTIONS : -n : print without the triling newline\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_echo (char ** array)"

.PP
Echo with -n option OPTIONS : -n : print without the triling newline\&. NOTES : you can add any number of n after -n if you want

.PP
\fBParameters\fP
.RS 4
\fIarray\fP array of strings 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 OK, error otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
