.TH "src/file/ft_file_tokens.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file/ft_file_tokens.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_command\fP * \fBremove_used_file_tokens\fP (\fBt_data\fP *data)"
.br
.RI "Removes all the tokens of file redirections allready used\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_command\fP * remove_used_file_tokens (\fBt_data\fP * data)"

.PP
Removes all the tokens of file redirections allready used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP data structure 
.RE
.PP
\fBReturns\fP
.RS 4
t_command* 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
