.TH "src/ft_free.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_free.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_command\fP (\fBt_garbage\fP *garbage, \fBt_command\fP *command)"
.br
.RI "Free one \fBt_command\fP structure with all that it contains\&. "
.ti -1c
.RI "void \fBfree_commands\fP (\fBt_garbage\fP *garbage, \fBt_command\fP **command)"
.br
.RI "Free \fBt_command\fP linked list structure with all that it contains\&. "
.ti -1c
.RI "void \fBfree_tokens\fP (\fBt_garbage\fP *garbage, \fBt_token\fP *token)"
.br
.RI "Free t_tokens linked list structure\&. "
.ti -1c
.RI "void \fBfree_files_struct\fP (\fBt_garbage\fP *garbage, \fBt_file\fP *file)"
.br
.RI "Free linked list of \fBt_file\fP structure\&. "
.ti -1c
.RI "void \fBfree_heredoc\fP (\fBt_garbage\fP *garbage, \fBt_tmp\fP *tmp)"
.br
.RI "Free heredoc structure\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_command (\fBt_garbage\fP * garbage, \fBt_command\fP * command)"

.PP
Free one \fBt_command\fP structure with all that it contains\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP \fBt_command\fP structure 
.RE
.PP

.SS "void free_commands (\fBt_garbage\fP * garbage, \fBt_command\fP ** command)"

.PP
Free \fBt_command\fP linked list structure with all that it contains\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP head of \fBt_command\fP linked list structure 
.RE
.PP

.SS "void free_files_struct (\fBt_garbage\fP * garbage, \fBt_file\fP * file)"

.PP
Free linked list of \fBt_file\fP structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP head of \fBt_file\fP linked list structure 
.RE
.PP

.SS "void free_heredoc (\fBt_garbage\fP * garbage, \fBt_tmp\fP * tmp)"

.PP
Free heredoc structure\&. 
.PP
\fBParameters\fP
.RS 4
\fItmp\fP heredoc structure 
.RE
.PP

.SS "void free_tokens (\fBt_garbage\fP * garbage, \fBt_token\fP * token)"

.PP
Free t_tokens linked list structure\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP head of t_tokens linked list structure 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
