.TH "src/builtins/ft_pwd.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/ft_pwd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include <linux/limits\&.h>\fP
.br
\fR#include <limits\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_pwd\fP (\fBt_data\fP *data, char **array)"
.br
.RI "Print the current working directory\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
