.TH "src/ft_print_fd.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ft_print_fd.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBprintn_fd\fP (int fd, const char *str, size_t len)"
.br
.RI "Function used to write safely and exits if write failed\&. "
.ti -1c
.RI "ssize_t \fBprint_fd\fP (int fd, const char *str)"
.br
.RI "Function used to write safely and exits if write failed\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "ssize_t print_fd (int fd, const char * str)"

.PP
Function used to write safely and exits if write failed\&. 
.PP
\fBParameters\fP
.RS 4
\fIfd\fP file descriptor 
.br
\fIstr\fP string to print 
.RE
.PP
\fBReturns\fP
.RS 4
ssize_t number of character printed 
.RE
.PP

.SS "ssize_t printn_fd (int fd, const char * str, size_t len)"

.PP
Function used to write safely and exits if write failed\&. 
.PP
\fBParameters\fP
.RS 4
\fIfd\fP file descriptor 
.br
\fIstr\fP string to print 
.br
\fIlen\fP number of character to print 
.RE
.PP
\fBReturns\fP
.RS 4
ssize_t number of character printed 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
