.TH "src/parsing/ft_split_charset.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing/ft_split_charset.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "t_bool \fBis_charset\fP (char c, char *charset)"
.br
.ti -1c
.RI "char ** \fBft_split_charset\fP (const char *s, char *charset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "t_bool is_charset (char c, char * charset)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
