.TH "src/builtins/ft_unset.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins/ft_unset.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_unset\fP (\fBt_data\fP *data, char **array)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_unset (\fBt_data\fP * data, char ** array)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
