.TH "src/env/functions_utils.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/functions_utils.c
.SH SYNOPSIS
.br
.PP
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlen_choose_c\fP (const char *str, char c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t ft_strlen_choose_c (const char * str, char c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
