.TH "src/parsing/functions_utils_parsing.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing/functions_utils_parsing.c
.SH SYNOPSIS
.br
.PP
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "t_bool \fBis_dollar\fP (char *str)"
.br
.ti -1c
.RI "char * \fBfill_string\fP (char *result, char *temp)"
.br
.ti -1c
.RI "t_bool \fBdetect_quote\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "t_bool detect_quote (const char * str)"

.SS "char * fill_string (char * result, char * temp)"

.SS "t_bool is_dollar (char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
