.TH "src/env/functions_utils_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/functions_utils_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_var\fP * \fBft_varlast\fP (\fBt_var\fP *var)"
.br
.ti -1c
.RI "void \fBft_varsadd_back\fP (\fBt_var\fP **var, \fBt_var\fP *new)"
.br
.ti -1c
.RI "\fBt_params\fP * \fBft_paramlast\fP (\fBt_params\fP *params)"
.br
.ti -1c
.RI "void \fBft_paramsadd_back\fP (\fBt_params\fP **params, \fBt_params\fP *new)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_params\fP * ft_paramlast (\fBt_params\fP * params)"

.SS "void ft_paramsadd_back (\fBt_params\fP ** params, \fBt_params\fP * new)"

.SS "\fBt_var\fP * ft_varlast (\fBt_var\fP * var)"

.SS "void ft_varsadd_back (\fBt_var\fP ** var, \fBt_var\fP * new)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
