.TH "src/garbage/garbage.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/garbage/garbage.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <readline/readline\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgarbage_init\fP (\fBt_garbage\fP *garbage)"
.br
.RI "Get the garbage object\&. "
.ti -1c
.RI "void \fBadd_to_garbage\fP (\fBt_garbage\fP *garbage, void *ptr)"
.br
.RI "Add a pointer to the garbage list\&. "
.ti -1c
.RI "void \fBfree_garbage\fP (\fBt_garbage\fP *garbage)"
.br
.RI "Free the garbage\&. "
.ti -1c
.RI "void * \fBmalloc_gb\fP (\fBt_garbage\fP *garbage, size_t size)"
.br
.RI "Replace the original malloc by storing the created adresses into a garbage to remove them afterwards\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_to_garbage (\fBt_garbage\fP * garbage, void * ptr)"

.PP
Add a pointer to the garbage list\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP pointer to add 
.RE
.PP

.SS "void free_garbage (\fBt_garbage\fP * garbage)"

.PP
Free the garbage\&. 
.SS "void garbage_init (\fBt_garbage\fP * garbage)"

.PP
Get the garbage object\&. 
.PP
\fBReturns\fP
.RS 4
t_garbage* garbage access
.RE
.PP
Initialize the garbage and sets the values to 0 
.SS "void * malloc_gb (\fBt_garbage\fP * garbage, size_t size)"

.PP
Replace the original malloc by storing the created adresses into a garbage to remove them afterwards\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP number of bytes to allocates 
.RE
.PP
\fBReturns\fP
.RS 4
void* 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
