.TH "src/env/get_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/get_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_var\fP * \fBfill_var\fP (char *envp[], size_t *i)"
.br
.ti -1c
.RI "\fBt_env_vars\fP * \fBget_env\fP (char *envp[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_var\fP * fill_var (char * envp[], size_t * i)"

.SS "\fBt_env_vars\fP * get_env (char * envp[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
