.TH "src/lexer/lexer.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lexer/lexer.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_TOKENS\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBlexer\fP (const char *line)"
.br
.RI "Create tokens (small chunks) a line with the quotes and operators\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_TOKENS   1024"

.SH "Function Documentation"
.PP 
.SS "char ** lexer (const char * line)"

.PP
Create tokens (small chunks) a line with the quotes and operators\&. Handle spaces, quotes (' and ') and shell operator (|, <, <<, >, >>)\&. Return an array of tokens (strings), NULL terminated\&.

.PP
\fBParameters\fP
.RS 4
\fIline\fP line to tokenise 
.RE
.PP
\fBReturns\fP
.RS 4
Array of strings 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
