.TH "src/lexer/lexer.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lexer/lexer.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBlexer\fP (\fBt_garbage\fP *garbage, const char *line)"
.br
.RI "Create tokens (small chunks) a line with the quotes and operators\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
