.TH "tests/src/main.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/main.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'tests\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBset_up\fP (void)"
.br
.ti -1c
.RI "void \fBtear_down\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void )"

.SS "void set_up (void )"

.SS "void tear_down (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
