.TH "src/main.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fR#include 'data_structure\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv, char **envp)"
.br
.RI "Main function\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv, char ** envp)"

.PP
Main function\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP number of argument 
.br
\fIargv\fP array of arguments 
.br
\fIenvp\fP environment 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 OK, error otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
