.TH "src/parsing/parsing_quotes_double.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing/parsing_quotes_double.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
