.TH "src/parsing/parsing.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parsing/parsing.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBparse_line\fP (char *line)"
.br
.RI "Prototype for parsing\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char ** parse_line (char * line)"

.PP
Prototype for parsing\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP line to parse 
.RE
.PP
\fBReturns\fP
.RS 4
char** 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
