.TH "s_data" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_data
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_garbage\fP \fBgarbage\fP"
.br
.ti -1c
.RI "\fBt_env_vars\fP \fBenv\fP"
.br
.ti -1c
.RI "\fBt_command\fP * \fBcommand\fP"
.br
.ti -1c
.RI "int \fBret\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_command\fP* s_data::command"

.SS "\fBt_env_vars\fP s_data::env"

.SS "\fBt_garbage\fP s_data::garbage"

.SS "int s_data::ret"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
