.TH "s_element" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_element \- Basic node for an element of a linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <garbage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic node for an element of a linked list\&. 
.SH "Field Documentation"
.PP 
.SS "void* s_element::next"

.SS "void* s_element::ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
