.TH "s_garbage" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_garbage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <garbage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBn_elements\fP"
.br
.ti -1c
.RI "\fBt_element\fP * \fBhead\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_element\fP* s_garbage::head"

.SS "size_t s_garbage::n_elements"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
