.TH "s_lexer_state" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_lexer_state
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBi\fP"
.br
.ti -1c
.RI "unsigned int \fBj\fP"
.br
.ti -1c
.RI "unsigned int \fBstart\fP"
.br
.ti -1c
.RI "t_bool \fBin_single_quote\fP"
.br
.ti -1c
.RI "t_bool \fBin_double_quote\fP"
.br
.ti -1c
.RI "char ** \fBtokens\fP"
.br
.ti -1c
.RI "const char * \fBline\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned int s_lexer_state::i"

.SS "t_bool s_lexer_state::in_double_quote"

.SS "t_bool s_lexer_state::in_single_quote"

.SS "unsigned int s_lexer_state::j"

.SS "const char* s_lexer_state::line"

.SS "unsigned int s_lexer_state::start"

.SS "char** s_lexer_state::tokens"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
