.TH "s_params" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_params\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_params\fP* s_params::next"

.SS "char* s_params::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
