.TH "s_supp" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_supp
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_var\fP * \fBcurr\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBprev_str\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_var\fP* s_supp::curr"

.SS "\fBt_var\fP* s_supp::prev_str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
