.TH "s_tmp" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_tmp \- Basic structure to help manipulating heredocs (tmp file)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <file\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic structure to help manipulating heredocs (tmp file) 
.SH "Field Documentation"
.PP 
.SS "int s_tmp::fd"

.SS "char* s_tmp::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
