.TH "s_token" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_token
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <minishell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "struct \fBs_token\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBs_token\fP* s_token::next"

.SS "char* s_token::str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
