.TH "s_token" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_token \- Basic structure of linked list of strings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <data_structure\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "struct \fBs_token\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic structure of linked list of strings\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBs_token\fP* s_token::next"

.SS "char* s_token::str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
