.TH "s_var" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_var
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_var\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "\fBt_params\fP * \fBhead_params\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t s_var::count"

.SS "\fBt_params\fP* s_var::head_params"

.SS "\fBt_var\fP* s_var::next"

.SS "char* s_var::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
