.TH "s_vars" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_vars
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <env\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_var\fP * \fBprev_str\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBprev_str_1\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBcurr_str\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBcurr_str_1\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBcurr\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBcurr_1\fP"
.br
.ti -1c
.RI "\fBt_var\fP * \fBtemp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBt_var\fP* s_vars::curr"

.SS "\fBt_var\fP* s_vars::curr_1"

.SS "\fBt_var\fP* s_vars::curr_str"

.SS "\fBt_var\fP* s_vars::curr_str_1"

.SS "\fBt_var\fP* s_vars::prev_str"

.SS "\fBt_var\fP* s_vars::prev_str_1"

.SS "\fBt_var\fP* s_vars::temp"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
