.TH "src/exec/search_command.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exec/search_command.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsearch_command\fP (\fBt_command\fP *command, char **tokens, int ret)"
.br
.RI "Search if command is a builtin or not\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int search_command (\fBt_command\fP * command, char ** tokens, int ret)"

.PP
Search if command is a builtin or not\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP command structure 
.br
\fItokens\fP array of strings 
.br
\fIret\fP return value of previous command 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 if command found, 1 otherwise 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
