.TH "src/env/set_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/set_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBset_env\fP (\fBt_data\fP *data, char *envp[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void set_env (\fBt_data\fP * data, char * envp[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
