.TH "src/signals.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/signals.c
.SH SYNOPSIS
.br
.PP
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <readline/readline\&.h>\fP
.br
\fR#include <signal\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsignal_handler\fP (int sig, siginfo_t *info, void *context)"
.br
.RI "Signal handler Ctrl+C = SIGINT -> print "^C" and displays a new prompt on a new line\&. Ctrl+\\ = SIGQUIT -> do nothing\&. "
.ti -1c
.RI "int \fBsignal_init\fP (void)"
.br
.RI "Main function for initialising signals\&. "
.ti -1c
.RI "void \fBreset_signal_default\fP (void)"
.br
.RI "Function to reset signals to default\&. "
.ti -1c
.RI "void \fBignore_signal\fP (void)"
.br
.RI "Function to ignore certain signals\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ignore_signal (void )"

.PP
Function to ignore certain signals\&. 
.SS "void reset_signal_default (void )"

.PP
Function to reset signals to default\&. 
.SS "void signal_handler (int sig, siginfo_t * info, void * context)"

.PP
Signal handler Ctrl+C = SIGINT -> print "^C" and displays a new prompt on a new line\&. Ctrl+\\ = SIGQUIT -> do nothing\&. Search for now signals : stty -a | grep -Ewoe '(intr|quit|susp|erase|kill|eof|eol|eol2) = [^;]+'; stty -a | grep -Ewoe '(swtch|start|stop|susp) = [^;]+'; stty -a | grep -Ewoe '(rprnt|werase|lnext|discard) = [^;]+';

.PP
\fBParameters\fP
.RS 4
\fIsig\fP Signal received\&. 
.br
\fIinfo\fP Information about the signal\&. 
.br
\fIcontext\fP Context of the signal\&. 
.RE
.PP

.SS "int signal_init (void )"

.PP
Main function for initialising signals\&. 
.PP
\fBReturns\fP
.RS 4
int 0 if the function ends correctly, -1 otherwise\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
