.TH "src/env/sort_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/sort_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbubble_sort\fP (\fBt_garbage\fP *garbage, \fBt_var\fP **head)"
.br
.ti -1c
.RI "void \fBsort_ascii_order\fP (\fBt_garbage\fP *garbage, \fBt_env_vars\fP *env)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bubble_sort (\fBt_garbage\fP * garbage, \fBt_var\fP ** head)"

.SS "void sort_ascii_order (\fBt_garbage\fP * garbage, \fBt_env_vars\fP * env)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
