.TH "src/env/swap_env.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/env/swap_env.c
.SH SYNOPSIS
.br
.PP
\fR#include 'env\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap_vars\fP (\fBt_garbage\fP *garbage, \fBt_var\fP **head, char *str, char *str_1)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void swap_vars (\fBt_garbage\fP * garbage, \fBt_var\fP ** head, char * str, char * str_1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
