.TH "tests/src/parsing_quotes_double/testing_parsing_quotes_double.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/parsing_quotes_double/testing_parsing_quotes_double.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'stdlib\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include 'tests\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparsing_tests\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void parsing_tests (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
