.TH "tests/src/parsing_quotes_double/tests_fx_printing.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/parsing_quotes_double/tests_fx_printing.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtesting_ft_remove_near_quotes\fP (char *str, char *expected, char *new_str)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   0"

.SH "Function Documentation"
.PP 
.SS "void testing_ft_remove_near_quotes (char * str, char * expected, char * new_str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
