.TH "tests/src/parsing_quotes_double/tests_pars_sing_fx2.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/parsing_quotes_double/tests_pars_sing_fx2.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'stdlib\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include 'tests\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBchanges_all_single\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void changes_all_single (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
