.TH "tests/src/parsing_quotes_double/tests_pars_doub_fx1.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/parsing_quotes_double/tests_pars_doub_fx1.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'stdlib\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include 'tests\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBno_changes_double\fP (void)"
.br
.ti -1c
.RI "void \fBchanges_one_double_1\fP (void)"
.br
.ti -1c
.RI "void \fBchanges_one_double_2\fP (void)"
.br
.ti -1c
.RI "void \fBchanges_one_double_3\fP (void)"
.br
.ti -1c
.RI "void \fBchanges_one_double_4\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void changes_one_double_1 (void )"

.SS "void changes_one_double_2 (void )"

.SS "void changes_one_double_3 (void )"

.SS "void changes_one_double_4 (void )"

.SS "void no_changes_double (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
