.TH "tests/src/file/tests_heredoc.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/file/tests_heredoc.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrandom_file_name_creation\fP (void)"
.br
.ti -1c
.RI "void \fBcreating_heredoc\fP (void)"
.br
.ti -1c
.RI "void \fBcreating_heredoc_ctrl_d\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void creating_heredoc (void )"

.SS "void creating_heredoc_ctrl_d (void )"

.SS "void random_file_name_creation (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
