.TH "tests/src/file/tests_file.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/file/tests_file.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'tests\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtesting_file_name\fP (void)"
.br
.ti -1c
.RI "void \fBtest_create_file\fP (char *str, int perms)"
.br
.ti -1c
.RI "void \fBtear_down_files\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void tear_down_files (void )"

.SS "void test_create_file (char * str, int perms)"

.SS "void testing_file_name (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
