.TH "tests/src/file/testing_file.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/file/testing_file.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'tests\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfile_tests\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void file_tests (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
