.TH "tests/src/testing_lexer.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/src/testing_lexer.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'unity\&.h'\fP
.br
\fR#include 'unity_internals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_array\fP (char **array)"
.br
.ti -1c
.RI "void \fBlexer_simple\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void lexer_simple (void )"

.SS "void print_array (char ** array)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
