.TH "src/file/tmp_generator.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/file/tmp_generator.c
.SH SYNOPSIS
.br
.PP
\fR#include 'file\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'ft_printf\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_tmp\fP \fBcreate_tmp\fP (\fBt_garbage\fP *garbage, char *path, int nbr_try)"
.br
.RI "Create a tmp file, verify if it already exist, tries to open it to verify permissions, and returns the result\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
