.TH "src/token-utils.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/token-utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBcopy_toks\fP (\fBt_data\fP *data, \fBt_command\fP *command)"
.br
.RI "Creates a copy of all tokens that are in a command structure It's used for forks during exec\&. "
.ti -1c
.RI "void \fBprint_toks\fP (char **tokens)"
.br
.RI "Print tokens indexed\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
