.TH "src/lexer/tokens.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lexer/tokens.c
.SH SYNOPSIS
.br
.PP
\fR#include 'minishell\&.h'\fP
.br
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'file\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_command\fP * \fBtokeniser\fP (char **tokens, char **envp)"
.br
.RI "Creates a \fBt_command\fP structure that contains all the tokens Fills the command with the environment\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBt_command\fP * tokeniser (char ** tokens, char ** envp)"

.PP
Creates a \fBt_command\fP structure that contains all the tokens Fills the command with the environment\&. 
.PP
\fBParameters\fP
.RS 4
\fItokens\fP tokens 
.br
\fIenvp\fP environment 
.RE
.PP
\fBReturns\fP
.RS 4
t_command* pointer if OK, NULL if it fails 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
