.TH "src/token-utils.c" 3 "Minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/token-utils.c
.SH SYNOPSIS
.br
.PP
\fR#include 'garbage\&.h'\fP
.br
\fR#include 'minishell\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBcopy_toks\fP (\fBt_command\fP *command)"
.br
.RI "Creates a copy of all tokens that are in a command structure It's used for forks during exec\&. "
.ti -1c
.RI "void \fBprint_toks\fP (char **tokens)"
.br
.RI "Print tokens indexed\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char ** copy_toks (\fBt_command\fP * command)"

.PP
Creates a copy of all tokens that are in a command structure It's used for forks during exec\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP command structure 
.RE
.PP
\fBReturns\fP
.RS 4
char** copy of tokens 
.RE
.PP

.SS "void print_toks (char ** tokens)"

.PP
Print tokens indexed\&. 
.PP
\fBParameters\fP
.RS 4
\fItokens\fP tokens to print 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Minishell from the source code\&.
