name: 42 Norminette

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Norminette
        run: python3 -m pip install norminette
      
      - name: Run Norminette on SRCS and INCS
        run: |
          norminette src inc tests/inc tests/src | tee norm_results.txt
          if grep -q "Error" norm_results.txt; then exit 1; fi
